export const BEGIN_LOADING = "BEGIN_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
export const SHOW_ERROR = "SHOW_ERROR";
export const ADD_QUESTION = "ADD_QUESTION";
export const JUMP_TO_QUESTION = "JUMP_TO_QUESTION";
export const UPDATE_ANSWERS = "UPDATE_ANSWERS";
export const SELECT_ANSWER = "SELECT_ANSWER";
export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
